# Generated by Django 5.2.4 on 2025-12-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsorderitem',
            old_name='ss_virtual_stock',
            new_name='ds_virtual_stock',
        ),
    ]
