# Generated by Django 5.2.4 on 2025-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargodetails',
            name='cargo_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cargodetails',
            name='cargo_mobile_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cargodetails',
            name='parcel_size',
            field=models.CharField(max_length=100),
        ),
    ]
