# Generated by Django 5.2.4 on 2025-11-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CRM', 'CRM'), ('ASM', 'ASM'), ('SS', 'Super Stockist'), ('DS', 'Distributor')], db_index=True, max_length=10),
        ),
    ]
