# Generated by Django 5.2.4 on 2026-02-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stock_location',
            field=models.CharField(choices=[('DELHI', 'Delhi Stock'), ('MUMBAI', 'Mumbai Stock')], db_index=True, default='DELHI', max_length=10),
        ),
    ]
