# Generated by Django 5.2.4 on 2026-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_stock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CRM', 'CRM'), ('ASM', 'ASM'), ('SS', 'Super Stockist'), ('DS', 'Distributor'), ('HR', 'HR')], db_index=True, max_length=10),
        ),
    ]
