# Generated by Django 5.2.4 on 2026-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
