# Generated by Django 5.2.4 on 2025-12-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartyItemSheet',
            new_name='SamplingSheet',
        ),
    ]
