# Generated by Django 5.2.4 on 2025-12-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0002_rename_partyitemsheet_samplingsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotInStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('original_quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('party_name', models.CharField(max_length=255)),
                ('order_no', models.CharField(max_length=100)),
                ('balance_qty', models.PositiveIntegerField()),
            ],
        ),
    ]
