# Generated by Django 5.2.4 on 2025-12-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0003_notinstockreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportCouponRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50)),
                ('coupon_number', models.CharField(max_length=50)),
            ],
        ),
    ]
