# Generated by Django 5.2.4 on 2025-12-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0004_passportcouponrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassportCouponRecord',
        ),
    ]
