# Generated by Django 5.2.4 on 2026-01-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0005_delete_passportcouponrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingsheet',
            name='mahotsav_dispatch_quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
