# Generated by Django 5.2.4 on 2026-01-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0006_samplingsheet_mahotsav_dispatch_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahotsav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(max_length=255)),
                ('party_name', models.CharField(max_length=255)),
                ('mahotsav_dispatch_quantity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
