# Generated by Django 5.2.4 on 2026-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0007_mahotsav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahotsav',
            name='crm_name',
            field=models.CharField(max_length=100),
        ),
    ]
