# Generated by Django 5.2.4 on 2026-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0008_alter_mahotsav_crm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahotsav',
            name='dinner_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mahotsav',
            name='gas_stove',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mahotsav',
            name='kitchen_cookware',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
