# Generated by Django 5.2.4 on 2026-05-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherinfo', '0009_mahotsav_dinner_set_mahotsav_gas_stove_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplingsheet',
            old_name='items',
            new_name='sampling_Items',
        ),
        migrations.RemoveField(
            model_name='samplingsheet',
            name='mahotsav_dispatch_quantity',
        ),
        migrations.AddField(
            model_name='samplingsheet',
            name='sixty_days_Items',
            field=models.TextField(default=1, help_text='Comma separated item codes'),
            preserve_default=False,
        ),
    ]
