# Generated by Django 5.2.4 on 2026-09-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASMSSAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('asm', models.ForeignKey(limit_choices_to={'role': 'ASM'}, on_delete=django.db.models.deletion.CASCADE, related_name='asm_assignments', to=settings.AUTH_USER_MODEL)),
                ('ss', models.ForeignKey(limit_choices_to={'role': 'SS'}, on_delete=django.db.models.deletion.CASCADE, related_name='asm_assignments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asm', 'is_active'], name='asm_active_assignments_idx'), models.Index(fields=['ss', 'is_active'], name='ss_active_assignments_idx')],
                'constraints': [models.UniqueConstraint(fields=('asm', 'ss'), name='unique_asm_ss_assignment')],
            },
        ),
    ]
