# Generated by Django 5.2.4 on 2026-09-16 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asmssassignment',
            name='unique_asm_ss_assignment',
        ),
        migrations.AddConstraint(
            model_name='asmssassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asm', 'ss'), name='unique_active_asm_ss_assignment'),
        ),
    ]
