# Generated by Django 5.2.4 on 2025-07-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssorder',
            name='party_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
