# Generated by Django 5.2.4 on 2025-07-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ssorder_party_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMVerifiedOrderScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('sale_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('is_auto_applied', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_schemes', to='orders.crmverifiedorder')),
            ],
        ),
    ]
