# Generated by Django 5.2.4 on 2025-09-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dispatchorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatchOrder',
        ),
    ]
