# Generated by Django 5.2.4 on 2025-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmverifiedorderitem',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
