# Generated by Django 5.2.4 on 2025-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_crmverifiedorderitem_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmverifiedorder',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HOLD', 'Hold')], db_index=True, max_length=20),
        ),
    ]
