# Generated by Django 5.2.4 on 2025-09-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ssorder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssorder',
            name='notes',
        ),
    ]
