# Generated by Django 5.2.4 on 2025-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_ssorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
