# Generated by Django 5.2.4 on 2025-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ssorder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmverifiedorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='crmverifiedorder',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='crmverifiedorder',
            name='punched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
