# Generated by Django 5.2.4 on 2025-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_crmverifiedorder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmverifiedorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmverifiedorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crmverifiedorder',
            name='punched',
            field=models.BooleanField(default=False),
        ),
    ]
