# Generated by Django 5.2.4 on 2025-09-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_crmverifiedorder_notes_crmverifiedorder_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmverifiedorder',
            name='punched',
        ),
    ]
