# Generated by Django 5.2.4 on 2025-09-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_crmverifiedorder_punched'),
        ('products', '0002_product_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePendingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pending_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_pending_stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Live Pending Stock',
                'verbose_name_plural': 'Live Pending Stock',
                'unique_together': {('product',)},
            },
        ),
    ]
