# Generated by Django 5.2.4 on 2025-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pendingorderitemsnapshot_delete_livependingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmverifiedorder',
            name='punched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
