# Generated by Django 5.2.4 on 2025-10-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_crmverifiedorder_punched'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssorderitem',
            name='ss_virtual_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
