# Generated by Django 5.2.4 on 2025-10-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_ssorderitem_ss_virtual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmverifiedorderitem',
            name='ss_virtual_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
