# Generated by Django 5.2.4 on 2025-11-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_crmverifiedorderitem_ss_virtual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssorder',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
