# Generated by Django 5.2.4 on 2025-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_ssorder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmverifiedorder',
            name='dispatch_location',
            field=models.CharField(db_index=True, default='Delhi', max_length=50),
        ),
    ]
