# Generated by Django 5.2.4 on 2025-12-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_crmverifiedorder_dispatch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ssorder',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
    ]
