# Generated by Django 5.2.4 on 2025-11-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_crmverifiedorder_dispatch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='quantity',
        ),
    ]
