# Generated by Django 5.2.4 on 2026-01-13 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_dispatchorder_alter_ssorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchorder',
            options={'ordering': ['-order_packed_time']},
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='row_key',
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='order_packed_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
