# Generated by Django 5.2.4 on 2026-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_dispatchorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='order_packed_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
