# Generated by Django 5.2.4 on 2025-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_dispatchorder_row_key_dispatchorder_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='row_key',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
