# Generated by Django 5.2.4 on 2026-01-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_dispatchorder_order_packed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
