# Generated by Django 5.2.4 on 2026-03-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_dispatchorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmverifiedorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='crmverifiedorder',
            name='total_amount',
        ),
    ]
