# Generated by Django 5.2.4 on 2026-03-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_crmverifiedorder_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmverifiedorderitem',
            name='price',
        ),
    ]
