# Generated by Django 5.2.4 on 2025-11-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_dispatchorder_row_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='order_id',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='product',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='row_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
