# Generated by Django 5.2.4 on 2026-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_crmverifiedorderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dispatch_location', models.CharField(db_index=True, max_length=50)),
                ('order_packed_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('crm_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_record', to='orders.crmverifiedorderitem')),
            ],
            options={
                'ordering': ['-order_packed_time', '-updated_at'],
                'indexes': [models.Index(fields=['dispatch_location', 'order_packed_time'], name='orders_disp_dispatc_5fa865_idx'), models.Index(fields=['dispatch_location', 'updated_at'], name='orders_disp_dispatc_e3a800_idx'), models.Index(fields=['order_packed_time'], name='orders_disp_order_p_877133_idx'), models.Index(fields=['updated_at'], name='orders_disp_updated_1dd4dd_idx')],
            },
        ),
    ]
