# Generated by Django 5.2.4 on 2025-11-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_dispatchorder_order_id_dispatchorder_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='row_key',
            field=models.CharField(max_length=100),
        ),
    ]
