# Generated by Django 5.2.4 on 2026-09-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_dispatchrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatchOrder',
        ),
    ]
