# Generated by Django 5.2.4 on 2025-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_dispatchorder_row_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
