# Generated by Django 5.2.4 on 2025-11-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_dispatchorder1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatchOrder1',
        ),
    ]
