# Generated by Django 5.2.4 on 2025-11-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_delete_dispatchorder1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='row_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
