# Generated by Django 5.2.4 on 2026-03-25 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=150)),
                ('parcel_size', models.CharField(max_length=50)),
                ('cargo_location', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('party', models.ForeignKey(limit_choices_to={'role': 'SS'}, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
