# Generated by Django 5.2.4 on 2026-03-25 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('party',), name='unique_party_cargo'),
        ),
    ]
