# Generated by Django 5.2.4 on 2026-04-02 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_unique_party_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=10)),
                ('party', models.ForeignKey(limit_choices_to={'role': 'SS'}, on_delete=django.db.models.deletion.CASCADE, related_name='gst_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('party',), name='unique_party_gst')],
            },
        ),
    ]
