# Generated by Django 5.2.4 on 2025-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_name', models.CharField(blank=True, max_length=50, null=True)),
                ('live_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('cartoon_size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_type', models.CharField(choices=[('single', 'Single'), ('combo', 'Combo')], max_length=10)),
                ('conditions', models.JSONField(help_text='List of required product IDs and quantities')),
                ('rewards', models.JSONField(help_text='List of free product IDs and quantities')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
