# Generated by Django 5.2.4 on 2025-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
