# Generated by Django 5.2.4 on 2025-08-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='start_date',
        ),
    ]
