# Generated by Django 5.2.4 on 2025-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='virtual_stock',
            field=models.IntegerField(default=0),
        ),
    ]
