# Generated by Django 5.2.4 on 2025-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_virtual_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='virtual_stock',
        ),
    ]
