# Generated by Django 5.2.4 on 2025-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_virtual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='virtual_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
