# Generated by Django 5.2.4 on 2025-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_virtual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
