# Generated by Django 5.2.4 on 2025-09-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_moq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='moq',
        ),
    ]
