# Generated by Django 5.2.4 on 2025-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
