# Generated by Django 5.2.4 on 2025-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
