# Generated by Django 5.2.4 on 2025-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
