# Generated by Django 5.2.4 on 2025-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_quantity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rack_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
