# Generated by Django 5.2.4 on 2025-11-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mumbai_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
