# Generated by Django 5.2.4 on 2025-11-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_mumbai_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='in_box',
            field=models.BooleanField(default=False),
        ),
    ]
