# Generated by Django 5.2.4 on 2025-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_scheme_in_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ds_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
