# Generated by Django 5.2.4 on 2025-12-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_partyitemsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartyItemSheet',
        ),
    ]
