# Generated by Django 5.2.4 on 2026-09-19 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.CharField(blank=True, max_length=10, null=True)),
                ('new_price', models.CharField(blank=True, max_length=10, null=True)),
                ('old_ds_price', models.CharField(blank=True, max_length=10, null=True)),
                ('new_ds_price', models.CharField(blank=True, max_length=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applicable_from', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_price_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='products.product')),
            ],
        ),
    ]
