# Generated by Django 5.2.4 on 2026-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dlr_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
