# Generated by Django 5.2.4 on 2026-09-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_dlr_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='new_dlr_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='old_dlr_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
